Update travis.yml to fix failing tests
Due to the latest seen error message from Travis-CI

```bash
ERROR: npm is known not to run on Node.js v4.0.0
Node.js 4 is supported but the specific version you're running has
a bug known to break npm. Please update to at least ${rel.min} to use this
version of npm. You can find the latest release of Node.js at https://nodejs.org/
```
the node.js version of the 4.x release cycle was updated to the latest `4.8.4` release.